spring.application.name=JPA

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDB
spring.datasource.username=postgres
spring.datasource.password=sagar123

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true

#
#spring.security.user.name=sagar
#spring.security.user.password=pass

jwt.secretKey=7ygdyuf8jbaoXXYTBsljgfoajfh0k485u485ugh98u54u98u54u57+554834